SELECT *
FROM gold.dim_customers;

-- Find total customers by countries
SELECT country, COUNT(*) AS NoOfCustomers
FROM gold.dim_customers
WHERE country != 'n/a'
GROUP BY country
ORDER BY NoOfCustomers DESC;

-- Find total customers by gender
SELECT gender, COUNT (*) AS NoOfCustomers
FROM gold.dim_customers
WHERE gender != 'n/a'
GROUP BY gender
ORDER BY NoOfCustomers;
-- Find total products by category

-- What is the average costs in each category?

-- What is the total revenue generated for each category?

-- Find total revenue is generated by each customer

-- What is the distribution of sold items across countries?

-- Which 5 products generate the highest revenue?

-- What are the 5 worst-performing products in terms of sales?

-- How does sales magnitude vary across categories?

-- Do a few customers account for a large share of revenue?

-- How much does price vary across product categories?