SELECT *
FROM gold.dim_customers;

-- Find total customers by countries
SELECT country, COUNT(*) AS NoOfCustomers
FROM gold.dim_customers
WHERE country != 'n/a'
GROUP BY country
ORDER BY NoOfCustomers DESC;

-- Find total customers by gender
SELECT gender, COUNT (*) AS NoOfCustomers
FROM gold.dim_customers
WHERE gender != 'n/a'
GROUP BY gender
ORDER BY NoOfCustomers;

-- Find total products by category
SELECT category, COUNT(*)
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category;

-- What is the average costs in each category?
SELECT category, ROUND(AVG(cost), 2)
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category;

-- total revenue generated for each category? METHOD 1 _USed SubQuery
SELECT p.category, SUM(f.TotalSales)
FROM gold.dim_products p
LEFT JOIN (
	SELECT product_key, SUM(sales_amount) AS TotalSales
	FROM gold.fact_sales
	WHERE sales_amount IS NOT NULL
	GROUP BY product_key
) f
ON f.product_key = p.product_key
WHERE p.category IS NOT NULL AND f.product_key IS NOT NULL
GROUP BY p.category
ORDER BY SUM(f.TotalSales) DESC;


--- METHOD 2
SELECT category, 
SUM (CASE WHEN f.sales_amount IS NOT NULL THEN  f.sales_amount
	ELSE 0
END) AS TotalSales
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key = f.product_key
WHERE category IS NOT NULL
GROUP BY category
ORDER BY TotalSales DESC;



-- Find total revenue is generated by each customer
SELECT 
	CONCAT(c.first_name, ' ', c.last_name) AS Full_name, 
	f.customer_key, 
	SUM(f.sales_amount) AS TotalSales -- 3
FROM gold.fact_sales f -- 1
RIGHT JOIN gold.dim_customers c --1
ON c.customer_key = f.customer_key -- 1
WHERE sales_amount IS NOT NULL -- 2
GROUP BY f.customer_key, c.first_name, c.last_name -- 4
ORDER BY TotalSales DESC; -- 5



