SELECT *
FROM gold.dim_customers;

-- Find total customers by countries
SELECT country, COUNT(*) AS NoOfCustomers
FROM gold.dim_customers
WHERE country != 'n/a'
GROUP BY country
ORDER BY NoOfCustomers DESC;

-- Find total customers by gender
SELECT gender, COUNT (*) AS NoOfCustomers
FROM gold.dim_customers
WHERE gender != 'n/a'
GROUP BY gender
ORDER BY NoOfCustomers;

-- Find total products by category
SELECT category, COUNT(*)
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category;

-- What is the average costs in each category?
SELECT category, ROUND(AVG(cost), 2)
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category;

-- total revenue generated for each category? METHOD 1 _USed SubQuery
SELECT p.category, SUM(f.TotalSales)
FROM gold.dim_products p
LEFT JOIN (
	SELECT product_key, SUM(sales_amount) AS TotalSales
	FROM gold.fact_sales
	WHERE sales_amount IS NOT NULL
	GROUP BY product_key
) f
ON f.product_key = p.product_key
WHERE p.category IS NOT NULL AND f.product_key IS NOT NULL
GROUP BY p.category
ORDER BY SUM(f.TotalSales) DESC;


--- METHOD 2
SELECT category, 
SUM (CASE WHEN f.sales_amount IS NOT NULL THEN  f.sales_amount
	ELSE 0
END) AS TotalSales
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key = f.product_key
WHERE category IS NOT NULL
GROUP BY category
ORDER BY TotalSales DESC;



-- Find total revenue is generated by each customer

-- What is the distribution of sold items across countries?

-- Which 5 products generate the highest revenue?

-- What are the 5 worst-performing products in terms of sales?

-- How does sales magnitude vary across categories?

-- Do a few customers account for a large share of revenue?

-- How much does price vary across product categories?